### ISSUE TITLE
feat: multiblocks

### ISSUE THREAD

**Issue by balugaq** [IndustrialRevival/IndustrialRevival#12]
两种类型：
固定大小多方块结构（最大9x9x9）[x,y,z]
不定大小多方块结构（类型匠魂炉，在其他地方限定最大20x256x20）[x,y,z]

enum Axis {
    X, Y, Z
}

abstract 多方块控制器:
- boolean environmentCheck() —— 由这个多方块结构的控制器执行，单独线程，每20 tick执行一次，避免过大开销（优化由extend这个东西的人自己搞）
- void setLimit(int maxX, int maxY, int maxZ) —— 设置这个多方块结构的最大x，y，z
- int getLimitX(Axis axis) —— 获取这个多方块结构的最大x，y，z
- int getSize(Axis axis) —— （仅不定大小多方块结构）获取当前多方块结构的x,y,z大小
- int setLimitX(Axis axis) —— （仅不定大小多方块结构）由这个多方块结构的控制器持有，设置这个多方块结构的最大x,y,z

**Comment by lijinhong11** [comment]
mlgb

**Comment by balugaq** [comment]
9
